# version: "3.8"

# services:
#   mutxamelcf:
#     image: mutxamelcf-app
#     container_name: mutxamelcf
#     ports:
#       - "8080:8080"
#     networks:
#       - mutxanet
#     restart: unless-stopped

# networks:
#   mutxanet:
#     external: true
version: "3.8"

services:

  mutxamelcf:

    image: mutxamelcf-app

    container_name: mutxamelcf

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8080

      DB_URL: jdbc:oracle:thin:@oracle:1521/XE
      DB_USERNAME: user_web
      DB_PASSWORD: mtx25WEB

      MAIL_HOST: smtp.ionos.es
      MAIL_PORT: 587
      MAIL_USERNAME: contacto.web@mutxamelcf.es
      MAIL_PASSWORD: z!TWTHNqW9PctVi

    networks:
      - mutxanet

    restart: unless-stopped

networks:
  mutxanet:
    external: true