<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>dao</artifactId>
<!--  <parent>-->
<!--        <groupId>org.springframework.boot</groupId>-->
<!--        <artifactId>spring-boot-starter-parent</artifactId>-->
<!--        <version>3.3.5</version>  Asegúrate de usar la misma versión que en tu proyecto principal -->
<!--        <relativePath/>  Ajusta la ruta según tu estructura de proyecto -->
<!--    </parent>-->
	<parent>
	    <groupId>com.mikedev.mutxamelcf</groupId>
	    <artifactId>mutxamelcfWeb</artifactId>
	    <version>1.0</version>
	    <relativePath>../pom.xml</relativePath>
	</parent>
  <properties>
        <java.version>17</java.version>
        <spring.version>6.1.14</spring.version>
        <maven.compiler.source>11</maven.compiler.source>
  		<maven.compiler.target>11</maven.compiler.target>
  </properties>
  <dependencies>
  		<!-- Dependencia para Spring JDBC -->
	    <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
	
	    <!-- Dependencia para el conector JDBC de Oracle -->
	    <dependency>
	        <groupId>com.oracle.database.jdbc</groupId>
	        <artifactId>ojdbc8</artifactId>
	    </dependency>
	
	    <!-- Dependencia de Spring Context (para la inyección de dependencias) -->
  		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
		    <groupId>org.springframework.boot</groupId>
		    <artifactId>spring-boot-starter-security</artifactId>
		</dependency>
  </dependencies>
</project>
