spring.application.name=WebMtx
logging.level.org.springframework.security=DEBUG

#spring.mail.host=smtp.gmail.com
spring.mail.host=smtp.ionos.es
spring.mail.port=587
spring.mail.username=contacto.web@mutxamelcf.es
spring.mail.password=z!TWTHNqW9PctVi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Configuración de la base de datos
spring.datasource.url=jdbc:oracle:thin:@217.154.102.212:1521/XE
spring.datasource.username=user_web
spring.datasource.password=mtx25WEB
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
#spring.datasource.username=system
#spring.datasource.password=neko
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.hikari.maximum-pool-size=10
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true