-- ============================================================================
-- Estadísticas de partido: resultado numérico (goles a favor/en contra) y
-- estadísticas individuales por jugador (goles, asistencias, tarjetas), que
-- el cuerpo técnico introduce después de disputarse un partido. Además,
-- recordatorio automático al cuerpo técnico si el resultado no se ha
-- introducido pasadas un par de horas desde el partido.
--
-- PARTIDOS.RESULTADO (texto libre, ej. "3-1") se mantiene sin cambios por
-- compatibilidad con todas las pantallas que ya lo leen (admin web
-- calendario-resultados.html, Flutter MatchModel/mis_partidos_page/
-- calendario_page/convocatoria_form_page, etc.): la capa de servicio sigue
-- calculando y sobreescribiendo RESULTADO a partir de GOLES_FAVOR/
-- GOLES_CONTRA cada vez que estos se guardan, para que ese texto siga
-- reflejando el resultado numérico sin tener que tocar ningún consumidor
-- existente.
--
-- AVISO_RESULTADO_ENVIADO es un campo interno (NO expuesto en PartidoDTO ni
-- en ninguna respuesta de la API) que evita reenviar el recordatorio más de
-- una vez por partido.
--
-- PARTIDO_ESTADISTICAS_JUGADOR: una fila por jugador y partido. No hay
-- ninguna validación cruzada entre la suma de GOLES de los jugadores y
-- GOLES_FAVOR del partido (decisión ya tomada con el cliente: los goles en
-- propia puerta del rival cuentan en GOLES_FAVOR sin ser atribuibles a
-- ningún jugador propio).
--
-- La base de datos de este proyecto es Oracle (ver
-- spring.datasource.driver-class-name=oracle.jdbc.OracleDriver), por lo que
-- se usa NUMBER/VARCHAR2/IDENTITY y la sintaxis ALTER TABLE de Oracle.
--
-- IMPORTANTE: este script NO se ejecuta automáticamente (el proyecto no usa
-- Flyway/Liquibase). Debe ejecutarse a mano en dev y en producción ANTES de
-- desplegar el commit que añade la funcionalidad de estadísticas de partido
-- (PartidoEstadisticaJugadorDaoImpl / PartidoDaoImpl.obtenerPendientesDeAviso
-- Resultado / RecordatorioResultadoPartidoScheduler).
-- ============================================================================

-- 1) PARTIDOS: goles numéricos del resultado y bookkeeping del recordatorio.
ALTER TABLE PARTIDOS ADD (
    GOLES_FAVOR                 NUMBER NULL,
    GOLES_CONTRA                NUMBER NULL,
    AVISO_RESULTADO_ENVIADO     NUMBER(1) DEFAULT 0 NOT NULL
);
ALTER TABLE PARTIDOS ADD CONSTRAINT CK_PARTIDOS_AVISO_RESULTADO CHECK (AVISO_RESULTADO_ENVIADO IN (0, 1));

-- 2) PARTIDO_ESTADISTICAS_JUGADOR: estadísticas individuales por jugador y
--    partido (goles, asistencias, tarjetas amarillas, tarjeta roja).
CREATE TABLE PARTIDO_ESTADISTICAS_JUGADOR (
    ID                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PARTIDO_ID              NUMBER NOT NULL,
    JUGADOR_ID              NUMBER NOT NULL,
    GOLES                   NUMBER DEFAULT 0 NOT NULL,
    ASISTENCIAS             NUMBER DEFAULT 0 NOT NULL,
    TARJETAS_AMARILLAS      NUMBER DEFAULT 0 NOT NULL,
    TARJETA_ROJA            NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_PART_ESTAD_JUG_PARTIDO FOREIGN KEY (PARTIDO_ID) REFERENCES PARTIDOS(ID),
    CONSTRAINT FK_PART_ESTAD_JUG_JUGADOR FOREIGN KEY (JUGADOR_ID) REFERENCES JUGADORES(ID),
    CONSTRAINT UQ_PART_ESTAD_JUG_PART_JUG UNIQUE (PARTIDO_ID, JUGADOR_ID),
    CONSTRAINT CK_PART_ESTAD_JUG_ROJA CHECK (TARJETA_ROJA IN (0, 1))
);

CREATE INDEX IDX_PART_ESTAD_JUG_PARTIDO ON PARTIDO_ESTADISTICAS_JUGADOR (PARTIDO_ID);
