-- ============================================================================
-- Tabla PARTIDOS
--
-- Sustituye a la tabla RESULTADOS (una unica fila fija por CATEGORIA+EQUIPO,
-- sobreescrita cada semana) por un historial real de partidos: una fila por
-- partido, con histórico y partidos futuros. Además de que el admin web siga
-- pudiendo editarla, ahora también los entrenadores podrán crear/editar los
-- partidos de sus propios equipos desde la app móvil (mismo mecanismo de
-- permisos que ya existe para ENTRENAMIENTOS, vía EQUIPO_ID).
--
-- La base de datos de este proyecto es Oracle (ver
-- spring.datasource.driver-class-name=oracle.jdbc.OracleDriver), por lo que
-- se usa NUMBER/VARCHAR2/IDENTITY en lugar de sintaxis MySQL.
--
-- IMPORTANTE: este script NO se ejecuta automáticamente (el proyecto no usa
-- Flyway/Liquibase). Debe ejecutarse a mano en la base de datos de
-- producción ANTES de desplegar la rama feature/partidos-multiples-editables.
--
-- La tabla se crea VACÍA a propósito: no se migran datos desde RESULTADOS
-- (decisión ya tomada con el cliente). La tabla RESULTADOS no se toca ni se
-- elimina con este script.
-- ============================================================================

CREATE TABLE PARTIDOS (
    ID                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EQUIPO_ID               NUMBER NOT NULL,
    RIVAL                   VARCHAR2(150) NOT NULL,
    DIA                     DATE NULL,
    HORA                    VARCHAR2(10) NULL,
    CAMPO                   VARCHAR2(150) NULL,
    RESULTADO               VARCHAR2(20) NULL,
    USUARIO_ACTUALIZO_ID    NUMBER NULL,
    FECHA_ACTUALIZACION     TIMESTAMP NULL,
    FECHA_CREACION          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PARTIDOS_EQUIPO FOREIGN KEY (EQUIPO_ID) REFERENCES EQUIPO(ID)
);

CREATE INDEX IDX_PARTIDOS_EQUIPO ON PARTIDOS (EQUIPO_ID);
CREATE INDEX IDX_PARTIDOS_DIA ON PARTIDOS (DIA);
