-- ============================================================================
-- Calendario de entrenamientos: horarios semanales recurrentes por equipo,
-- que generan automáticamente sesiones concretas mes a mes; cancelación
-- individual de esas sesiones (con notificación); justificación informativa
-- de falta en adelanto por parte de jugadores/familias (sin necesidad de
-- aprobación); y cancelación de partidos (PARTIDOS) sin borrarlos.
--
-- HORARIOS_ENTRENAMIENTO: un equipo puede tener varios horarios fijos (p.ej.
-- martes y jueves a distinta hora). DIA_SEMANA sigue el mismo criterio que
-- java.time.DayOfWeek.getValue() (1=lunes .. 7=domingo).
--
-- SESIONES_ENTRENAMIENTO: instancias concretas de un horario (HORARIO_ID) o
-- sueltas (HORARIO_ID NULL, entrenamiento puntual sin recurrencia). La
-- UNIQUE(HORARIO_ID, FECHA) hace idempotente la generación automática:
-- Oracle permite múltiples NULLs en una UNIQUE, así que las sesiones sueltas
-- (HORARIO_ID NULL) no se ven afectadas por esa restricción.
--
-- JUSTIFICACIONES_FALTA_ENTRENAMIENTO: aviso informativo (no aprobación) de
-- que un jugador va a faltar a una sesión. UNIQUE(SESION_ID, JUGADOR_ID):
-- volver a justificar la misma sesión actualiza el motivo (upsert en la
-- capa de servicio), no crea una fila duplicada.
--
-- La base de datos de este proyecto es Oracle (ver
-- spring.datasource.driver-class-name=oracle.jdbc.OracleDriver), por lo que
-- se usa NUMBER/VARCHAR2/IDENTITY y la sintaxis ALTER TABLE de Oracle.
--
-- IMPORTANTE: este script NO se ejecuta automáticamente (el proyecto no usa
-- Flyway/Liquibase). Debe ejecutarse a mano en dev y en producción ANTES de
-- desplegar el commit que añade la funcionalidad de Calendario (HorarioEntre
-- namientoDaoImpl / SesionEntrenamientoDaoImpl / JustificacionFaltaEntrena
-- mientoDaoImpl / PartidoDaoImpl.cancelar).
-- ============================================================================

-- 1) HORARIOS_ENTRENAMIENTO: horario semanal fijo de un equipo.
CREATE TABLE HORARIOS_ENTRENAMIENTO (
    ID                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EQUIPO_ID               NUMBER NOT NULL,
    DIA_SEMANA              NUMBER(1) NOT NULL,
    HORA                    VARCHAR2(10) NOT NULL,
    LUGAR                   VARCHAR2(150) NULL,
    ACTIVO                  NUMBER(1) DEFAULT 1 NOT NULL,
    USUARIO_ACTUALIZO_ID    NUMBER NULL,
    FECHA_ACTUALIZACION     TIMESTAMP NULL,
    CONSTRAINT FK_HORARIOS_ENTRENO_EQUIPO FOREIGN KEY (EQUIPO_ID) REFERENCES EQUIPO(ID),
    CONSTRAINT FK_HORARIOS_ENTRENO_USUARIO FOREIGN KEY (USUARIO_ACTUALIZO_ID) REFERENCES USUARIOS_APP(ID),
    CONSTRAINT CK_HORARIOS_ENTRENO_DIA CHECK (DIA_SEMANA BETWEEN 1 AND 7),
    CONSTRAINT CK_HORARIOS_ENTRENO_ACTIVO CHECK (ACTIVO IN (0, 1))
);

CREATE INDEX IDX_HORARIOS_ENTRENO_EQUIPO ON HORARIOS_ENTRENAMIENTO (EQUIPO_ID);

-- 2) SESIONES_ENTRENAMIENTO: instancias concretas (generadas o sueltas).
CREATE TABLE SESIONES_ENTRENAMIENTO (
    ID                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EQUIPO_ID               NUMBER NOT NULL,
    HORARIO_ID              NUMBER NULL,
    FECHA                   DATE NOT NULL,
    HORA                    VARCHAR2(10) NULL,
    LUGAR                   VARCHAR2(150) NULL,
    ESTADO                  VARCHAR2(20) DEFAULT 'PROGRAMADA' NOT NULL,
    FECHA_CREACION          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_SESIONES_ENTRENO_EQUIPO FOREIGN KEY (EQUIPO_ID) REFERENCES EQUIPO(ID),
    CONSTRAINT FK_SESIONES_ENTRENO_HORARIO FOREIGN KEY (HORARIO_ID) REFERENCES HORARIOS_ENTRENAMIENTO(ID),
    CONSTRAINT CK_SESIONES_ENTRENO_ESTADO CHECK (ESTADO IN ('PROGRAMADA', 'CANCELADA')),
    CONSTRAINT UQ_SESIONES_ENTRENO_HOR_FECHA UNIQUE (HORARIO_ID, FECHA)
);

CREATE INDEX IDX_SESIONES_ENTRENO_EQ_FECHA ON SESIONES_ENTRENAMIENTO (EQUIPO_ID, FECHA);

-- 3) JUSTIFICACIONES_FALTA_ENTRENAMIENTO: aviso informativo de falta.
CREATE TABLE JUSTIFICACIONES_FALTA_ENTRENAMIENTO (
    ID                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SESION_ID               NUMBER NOT NULL,
    JUGADOR_ID              NUMBER NOT NULL,
    USUARIO_APP_ID          NUMBER NOT NULL,
    MOTIVO                  VARCHAR2(500) NULL,
    FECHA_CREACION          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_JUSTIF_FALTA_SESION FOREIGN KEY (SESION_ID) REFERENCES SESIONES_ENTRENAMIENTO(ID),
    CONSTRAINT FK_JUSTIF_FALTA_JUGADOR FOREIGN KEY (JUGADOR_ID) REFERENCES JUGADORES(ID),
    CONSTRAINT FK_JUSTIF_FALTA_USUARIO FOREIGN KEY (USUARIO_APP_ID) REFERENCES USUARIOS_APP(ID),
    CONSTRAINT UQ_JUSTIF_FALTA_SESION_JUGADOR UNIQUE (SESION_ID, JUGADOR_ID)
);

-- 4) PARTIDOS: se añade CANCELADO para poder cancelar un partido sin
--    borrarlo (se conserva su histórico y la convocatoria asociada, si la
--    tuviera).
ALTER TABLE PARTIDOS ADD (CANCELADO NUMBER(1) DEFAULT 0 NOT NULL);
ALTER TABLE PARTIDOS ADD CONSTRAINT CK_PARTIDOS_CANCELADO CHECK (CANCELADO IN (0, 1));
